apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: loki-datasource
  namespace: nok-bng
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: Loki
    type: loki
    uid: DS_LOKI
    access: proxy
    url: http://tel-loki:3100
    jsonData:
      timeout: 60
      maxLines: 1000