apiVersion: operator.gnmic.dev/v1alpha1
kind: Pipeline
metadata:
  namespace: nok-dia
  name: agg-gnmic-pipe-metrics
spec:
  clusterRef: dia-metrics
  enabled: true
  targetSelectors:
    - matchLabels:
        vendor: Nokia
  subscriptionSelectors:
    - matchLabels:
        type: dia
  outputs:
    outputSelectors:
      - matchLabels:
          type: dia-ext-output  
    processorRefs:
      - oper-state-to-int              
