apiVersion: operator.gnmic.dev/v1alpha1
kind: Pipeline
metadata:
  namespace: nok-dia
  name: gnmic-rt-stats
spec:
  clusterRef: dia-core-metrics
  enabled: true
  targetSelectors:
    - matchLabels:
        type: core
  subscriptionSelectors:
    - matchLabels:
        type: rt-stats
  outputs:
    outputSelectors:
      - matchLabels:
          type: dia-ext-output          
