apiVersion: nok.dev/v1alpha1
kind: NetworkHostTarget
metadata:
  name: clab-nok-dia-traffic-gen
  namespace: nok-dia
spec:
  address: 172.23.20.32
  hostname: clab-nok-dia-traffic-gen
  commonLabels:
    role: iperf3
    environment: production
