{
 "title": "Routing and Forwarding Stats",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "source",
    "label": "Source:",
    "query": {
     "query": "label_values(state_service_statistics_vpls_fdb_entries_allocated,source)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{job=\"gnmic-state\"}\n|= \"oper-name\"\n| json\n| source = \"$source\"\n| regexp \"\\\"oper-name\\\":\\\"(?P<Line>[^\\\"]+)\\\"\"\n| line_format \"{{ .Line }}\""
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{job=\"gnmic-state\"}\n|= \"version-string\"\n| json\n| source = \"$source\"\n| regexp `\"version-string\":\\s*\"(?P<short_version>.*?)\\s+Copyright` \n| line_format \"{{ .short_version }}\""
    }
   ]
  },
  {
   "title": "IPv4 Routes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "# Total BGP Routes",
     "type": "stat",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(state_router_route_table_unicast_ipv4_statistics_bgp_active_routes{source=\"$source\"})",
       "legendFormat": "Active"
      },
      {
       "expr": "sum(state_router_route_table_unicast_ipv4_statistics_bgp_available_routes{source=\"$source\"})",
       "legendFormat": "Available"
      }
     ]
    },
    {
     "title": "# Total ISIS Routes",
     "type": "stat",
     "gridPos": { "h": 6, "w": 7, "x": 7, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(state_router_route_table_unicast_ipv4_statistics_isis_active_routes{source=\"$source\"})",
       "legendFormat": "Active"
      },
      {
       "expr": "sum(state_router_route_table_unicast_ipv4_statistics_isis_available_routes{source=\"$source\"})",
       "legendFormat": "Available"
      }
     ]
    },
    {
     "title": "# Total OSPF Routes",
     "type": "stat",
     "gridPos": { "h": 6, "w": 7, "x": 14, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(state_router_route_table_unicast_ipv4_statistics_ospf_active_routes{source=\"$source\"})",
       "legendFormat": "Active"
      },
      {
       "expr": "sum(state_router_route_table_unicast_ipv4_statistics_ospf_available_routes{source=\"$source\"})",
       "legendFormat": "Available"
      }
     ]
    },
    {
     "title": "# Total Static Routes",
     "type": "stat",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(state_router_route_table_unicast_ipv4_statistics_static_active_routes{source=\"$source\"})",
       "legendFormat": "Active"
      },
      {
       "expr": "sum(state_router_route_table_unicast_ipv4_statistics_static_available_routes{source=\"$source\"})",
       "legendFormat": "Available"
      }
     ]
    },
    {
     "title": "# Total OSPFv3 Routes",
     "type": "stat",
     "gridPos": { "h": 6, "w": 10, "x": 11, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(state_router_route_table_unicast_ipv4_statistics_ospfv3_active_routes{source=\"$source\"})",
       "legendFormat": "Active"
      },
      {
       "expr": "sum(state_router_route_table_unicast_ipv4_statistics_ospfv3_available_routes{source=\"$source\"})",
       "legendFormat": "Available"
      }
     ]
    }
   ]
  },
  {
   "title": "IPv6 Routes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "# Total BGP Routes",
     "type": "stat",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(state_router_route_table_unicast_ipv6_statistics_bgp_active_routes{source=\"$source\"})",
       "legendFormat": "Active"
      },
      {
       "expr": "sum(state_router_route_table_unicast_ipv6_statistics_bgp_available_routes{source=\"$source\"})",
       "legendFormat": "Available"
      }
     ]
    },
    {
     "title": "# Total ISIS Routes",
     "type": "stat",
     "gridPos": { "h": 6, "w": 7, "x": 7, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(state_router_route_table_unicast_ipv6_statistics_isis_active_routes{source=\"$source\"})",
       "legendFormat": "Active"
      },
      {
       "expr": "sum(state_router_route_table_unicast_ipv6_statistics_isis_available_routes{source=\"$source\"})",
       "legendFormat": "Available"
      }
     ]
    },
    {
     "title": "# Total OSPFv3 Routes",
     "type": "stat",
     "gridPos": { "h": 6, "w": 7, "x": 14, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(state_router_route_table_unicast_ipv6_statistics_ospfv3_active_routes{source=\"$source\"})",
       "legendFormat": "Active"
      },
      {
       "expr": "sum(state_router_route_table_unicast_ipv6_statistics_ospfv3_available_routes{source=\"$source\"})",
       "legendFormat": "Available"
      }
     ]
    },
    {
     "title": "# Total Static Routes",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(state_router_route_table_unicast_ipv6_statistics_static_active_routes{source=\"$source\"})",
       "legendFormat": "Active"
      },
      {
       "expr": "sum(state_router_route_table_unicast_ipv6_statistics_static_available_routes{source=\"$source\"})",
       "legendFormat": "Available"
      }
     ]
    },
    {
     "title": "# Total SRV6 Routes",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 6, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(state_router_route_table_unicast_ipv6_statistics_srv6_active_routes{source=\"$source\"})",
       "legendFormat": "Active"
      },
      {
       "expr": "sum(state_router_route_table_unicast_ipv6_statistics_srv6_available_routes{source=\"$source\"})",
       "legendFormat": "Available"
      }
     ]
    },
    {
     "title": "# Total DHCPv6-NA Routes",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 11, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(state_router_route_table_unicast_ipv6_statistics_dhcpv6_na_active_routes{source=\"$source\"})",
       "legendFormat": "Active"
      },
      {
       "expr": "sum(state_router_route_table_unicast_ipv6_statistics_dhcpv6_na_available_routes{source=\"$source\"})",
       "legendFormat": "Available"
      }
     ]
    },
    {
     "title": "# Total DHCPv6-PD Routes",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(state_router_route_table_unicast_ipv6_statistics_dhcpv6_pd_active_routes{source=\"$source\"})",
       "legendFormat": "Active"
      },
      {
       "expr": "sum(state_router_route_table_unicast_ipv6_statistics_dhcpv6_pd_available_routes{source=\"$source\"})",
       "legendFormat": "Available"
      }
     ]
    }
   ]
  },
  { "title": "VPLS FDB Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "FDB Entries is Use",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_service_statistics_vpls_fdb_entries_in_use{source=\"$source\"}/state_service_statistics_vpls_fdb_entries_total{source=\"$source\"}*100",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "FDB Entries Allocated",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_service_statistics_vpls_fdb_entries_allocated{source=\"$source\"}/state_service_statistics_vpls_fdb_entries_total{source=\"$source\"}*100",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Limit Exceeded?",
   "type": "status-history",
   "description": "Confirms no software-defined or administrative scale thresholds have been violated.",
   "gridPos": { "h": 3, "w": 21, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "state_service_statistics_vpls_fdb_limit_exceeded{source=\"$source\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Table Full?",
   "type": "status-history",
   "description": "Confirms the FDB table has plenty of space; it will flip to 1 if your network runs out of MAC address slots",
   "gridPos": { "h": 3, "w": 21, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "state_service_statistics_vpls_fdb_table_full{source=\"$source\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hardware Limit Exceeded?",
   "type": "status-history",
   "description": "Confirms the physical line card hardware limits have not been breached",
   "gridPos": { "h": 3, "w": 21, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "state_service_statistics_vpls_fdb_hw_limit_exceeded{source=\"$source\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}