{
 "title": "System Levels and Resource Usage per Device",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "source",
    "label": "Source:",
    "query": {
     "query": "label_values(state_system_cpu_summary_usage_cpu_usage,source)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{job=\"gnmic-state\"}\n|= \"oper-name\"\n| json\n| source = \"$source\"\n| regexp \"\\\"oper-name\\\":\\\"(?P<Line>[^\\\"]+)\\\"\"\n| line_format \"{{ .Line }}\""
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{job=\"gnmic-state\"}\n|= \"version-string\"\n| json\n| source = \"$source\"\n| regexp `\"version-string\":\\s*\"(?P<short_version>.*?)\\s+Copyright` \n| line_format \"{{ .short_version }}\""
    }
   ]
  },
  { "title": "System Level", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Used Memory [1m]",
   "type": "timeseries",
   "description": "Non available RAM memory",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(state_system_memory_pools_summary_total_in_use{source=\"$source\"}/state_system_memory_pools_summary_available_memory{source=\"$source\"} * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU System Load (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(state_system_cpu_summary_usage_cpu_usage{source=\"$source\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flash CF3 Storage Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(state_cpm_flash_percent_used{source=\"$source\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fan Speeds",
   "type": "gauge",
   "description": "Fan speed, max value between all the slots",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(state_chassis_fan_speed{source=\"$source\"}[30m]))",
     "legendFormat": "chassis {{chassis_chassis_number}} / slot {{fan_fan_slot}}"
    }
   ]
  },
  {
   "title": "Port In Discards",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(state_port_statistics_in_discards{source=\"$source\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Port Out Discards",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(state_port_statistics_out_discards{source=\"$source\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Network Traffic",
   "type": "timeseries",
   "description": "Total network traffic",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum((rate(state_port_ethernet_statistics_in_octets{source=\"$source\"}[5m]) + rate(state_port_ethernet_statistics_out_octets{source=\"$source\"}[5m]))*8)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_system_up_time{source=\"$source\"}/1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Temps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPM Temps vs Threshold",
     "type": "status-history",
     "description": "CPM temp vs Threshold",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "state_cpm_hardware_data_temperature{source=\"$source\"}",
       "legendFormat": "Temp"
      },
      {
       "expr": "state_cpm_hardware_data_temperature_threshold{source=\"$source\"}>0",
       "legendFormat": "Threshold"
      }
     ]
    },
    {
     "title": "Card Temps vs Threshold",
     "type": "status-history",
     "description": "Card temp vs Threshold",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "state_card_hardware_data_temperature{source=\"$source\"}",
       "legendFormat": "Temp"
      },
      {
       "expr": "state_card_hardware_data_temperature_threshold{source=\"$source\"}",
       "legendFormat": "Threshold"
      }
     ]
    },
    {
     "title": "MDA Temps vs Threshold",
     "type": "status-history",
     "description": "MDA temp vs Threshold",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "max(state_card_mda_hardware_data_temperature{source=\"$source\"})",
       "legendFormat": "Temp"
      },
      {
       "expr": "max(state_card_mda_hardware_data_temperature_threshold{source=\"$source\"}>0)",
       "legendFormat": "Threshold"
      }
     ]
    }
   ]
  },
  {
   "title": "Resourse Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "#SAPs",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "state_system_resource_usage_sap_allocated{source=\"$source\"}/state_system_resource_usage_sap_total{source=\"$source\"}*100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "#SAP EGRESS QOS POLICIES",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 7, "x": 7, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "state_system_resource_usage_sap_egress_qos_policies_allocated{source=\"$source\"}/state_system_resource_usage_sap_egress_qos_policies_total{source=\"$source\"}*100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "#SAP INGRESS QOS POLICIES",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 7, "x": 14, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "state_system_resource_usage_sap_ingress_qos_policies_allocated{source=\"$source\"}/state_system_resource_usage_sap_ingress_qos_policies_total{source=\"$source\"}*100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "# VPLS SAPs",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "state_system_resource_usage_sap_vpls_allocated{source=\"$source\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "# VPRN SAPs",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "state_system_resource_usage_sap_vprn_allocated{source=\"$source\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "# IES SAPs",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "state_system_resource_usage_sap_ies_allocated{source=\"$source\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "# E-PIPE SAPs",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "state_system_resource_usage_sap_epipe_allocated{source=\"$source\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "# C-PIPE SAPs",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "state_system_resource_usage_sap_cpipe_allocated{source=\"$source\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "# C-PIPE SAPs",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "state_system_resource_usage_sap_ipipe_allocated{source=\"$source\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "# VPLS",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "state_system_resource_usage_service_vpls_allocated{source=\"$source\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "# VPRN",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "state_system_resource_usage_service_vprn_allocated{source=\"$source\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "# IES",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "state_system_resource_usage_service_ies_allocated{source=\"$source\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "# E-PIPE",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "state_system_resource_usage_service_epipe_allocated{source=\"$source\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "# C-PIPE",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "state_system_resource_usage_service_cpipe_allocated{source=\"$source\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "# I-PIPE",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "state_system_resource_usage_service_ipipe_allocated{source=\"$source\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}