apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gnmic-metrics
  namespace: nok-bng
  # labels:
  #   release: bng-ext-output  # Match your Prometheus serviceMonitorSelector
spec:
  selector:
    matchLabels:
      operator.gnmic.dev/service-type: prometheus-output      
  namespaceSelector:
    matchNames:
      - nok-bng   
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
      # relabelings:
      #   - sourceLabels: [source]
      #     regex: 'nok-bng/(.*)'
      #     targetLabel: source
      #     action: replace      

