apiVersion: operator.gnmic.dev/v1alpha1
kind: Pipeline
metadata:
  namespace: nok-dia
  name: gnmic-pipe-port-drops-all
spec:
  clusterRef: dia-metrics
  enabled: true
  targetSelectors:
    - matchLabels:
        vendor: Nokia
  subscriptionSelectors:
    - matchLabels:
        type: portDrops
  outputs:
    outputSelectors:
      - matchLabels:
          type: dia-ext-output           
