apiVersion: operator.gnmic.dev/v1alpha1
kind: Pipeline
metadata:
  namespace: nok-dia
  name: sros-vpls-fdb
spec:
  clusterRef: dia-metrics
  enabled: true
  targetSelectors:
    - matchLabels:
        role: core
  subscriptionSelectors:
    - matchLabels:
        type: vpls-fdb
  outputs:
    outputSelectors:
      - matchLabels:
          type: dia-ext-output
