apiVersion: config.sdcio.dev/v1alpha1
kind: Config
metadata:
  name: ixr-e2-21-vpls-301-sros
  namespace: nok-dia
  labels:
    config.sdcio.dev/targetName: clab-nok-dia-ixr-e2-21
    config.sdcio.dev/targetNamespace: nok-dia
spec:
  priority: 10
  revertive: true
  config: 
  - path: /configure
    value:
      port:
        port-id: "1/1/c10/1"
        admin-state: "enable"
        ethernet:
          mode: "access"
          encap-type: "dot1q"  
      service:
        customer:
          customer-name: "CUST-301"
          customer-id: 301          
        vpls:
          - service-name: "301"
            admin-state: "enable"
            customer: "CUST-301"
            routed-vpls: {}
            bgp:
              - bgp-instance: 1
                route-distinguisher: "192.0.2.5:301"
                route-target:
                  export: "target:301:20000"
                  import: "target:301:20000"
            bgp-evpn:
              evi: 301
              ignore-mtu-mismatch: true
              routes:
                mac-ip:
                  cfm-mac: true
              mpls:
                - bgp-instance: 1
                  admin-state: "enable"
                  mh-mode: "access"
                  auto-bind-tunnel:
                    resolution: "filter"
                    resolution-filter:
                      sr-isis: true
            sap:
              - sap-id: "1/1/c10/1:0"