{
 "title": "BNG State and Resource Availability",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "DS_LOKI", "label": "DS_LOKI", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "BNG State and Redundancy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Unavailability Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(\n  absent_over_time(\n    {__name__=~\"state_system_cpu_summary_usage_cpu_time|state_system_resource_usage_subscriber_next_hop_entries_total|state_router_interface_statistics_ip_in_octets\", source=~\".*bngt-bng1\"}[$__interval]\n  ),\n  \"source\", \"nok-bng/clab-sros-bngt-bng1\", \"\", \"\"\n)\nor\ncount by (source) (\n  {__name__=~\"state_system_cpu_summary_usage_cpu_time|state_system_resource_usage_subscriber_next_hop_entries_total|state_router_interface_statistics_ip_in_octets\", source=~\".*bngt-bng1\"}\n) * 0",
     "legendFormat": "{{source}}"
    },
    {
     "expr": "label_replace(\n  absent_over_time(\n    {__name__=~\"state_system_cpu_summary_usage_cpu_time|state_system_resource_usage_subscriber_next_hop_entries_total|state_router_interface_statistics_ip_in_octets\", source=~\".*bngt-bng2\"}[$__interval]\n  ),\n  \"source\", \"nok-bng/clab-sros-bngt-bng2\", \"\", \"\"\n)\nor\ncount by (source) (\n  {__name__=~\"state_system_cpu_summary_usage_cpu_time|state_system_resource_usage_subscriber_next_hop_entries_total|state_router_interface_statistics_ip_in_octets\", source=~\".*bngt-bng2\"}\n) * 0",
     "legendFormat": "{{source}}"
    },
    {
     "expr": "label_replace(\n  absent_over_time(\n    {__name__=~\"state_system_cpu_summary_usage_cpu_time|state_system_resource_usage_subscriber_next_hop_entries_total|state_router_interface_statistics_ip_in_octets\", source=~\".*bngt-agg\"}[$__interval]\n  ),\n  \"source\", \"nok-bng/clab-sros-bngt-agg\", \"\", \"\"\n)\nor\ncount by (source) (\n  {__name__=~\"state_system_cpu_summary_usage_cpu_time|state_system_resource_usage_subscriber_next_hop_entries_total|state_router_interface_statistics_ip_in_octets\", source=~\".*bngt-agg\"}\n) * 0",
     "legendFormat": "{{source}}"
    },
    {
     "expr": "label_replace(\n  absent_over_time(\n    {__name__=~\"state_system_cpu_summary_usage_cpu_time|state_system_resource_usage_subscriber_next_hop_entries_total|state_router_interface_statistics_ip_in_octets\", source=~\".*bngt-core\"}[$__interval]\n  ),\n  \"source\", \"nok-bng/clab-sros-bngt-core\", \"\", \"\"\n)\nor\ncount by (source) (\n  {__name__=~\"state_system_cpu_summary_usage_cpu_time|state_system_resource_usage_subscriber_next_hop_entries_total|state_router_interface_statistics_ip_in_octets\", source=~\".*bngt-core\"}\n) * 0",
     "legendFormat": "{{source}}"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SRRP Adv. Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "state_service_vprn_subscriber_interface_group_interface_srrp_statistics_advertisement_interval_errors{source=~\".*clab-sros-bngt-bng1\", srrp_srrp_id=\"1\"}",
     "legendFormat": "{{source}}"
    },
    {
     "expr": "state_service_vprn_subscriber_interface_group_interface_srrp_statistics_advertisement_interval_errors{source=~\".*nok-bng/clab-sros-bngt-bng2\", srrp_srrp_id=\"1\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "SRRP Redundancy",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"gnmic-state\"} \n|~ \"srrp.*oper-state\" \n| json bngRouter=\"source\"\n| bngRouter=~\".*bng1.*\"\n| json operState=`updates[0].values[\"oper-state\"]`\n| label_format BNG1_OperState=\"{{.bngRouter}} {{.operState}}\""
    },
    {
     "direction": "backward",
     "expr": "{job=\"gnmic-state\"} \n|~ \"srrp.*oper-state\" \n| json bngRouter=\"source\"\n| bngRouter=~\".*bng2.*\"\n| json operState=`updates[0].values[\"oper-state\"]`\n| label_format BNG2_OperState=\"{{.bngRouter}} {{.operState}}\""
    }
   ]
  },
  {
   "title": "SRRP Adv. Discards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "state_service_vprn_subscriber_interface_group_interface_srrp_statistics_advertisement_interval_discards{source=~\".*bngt-bng1\", srrp_srrp_id=\"1\"}",
     "legendFormat": "{{source}}"
    },
    {
     "expr": "state_service_vprn_subscriber_interface_group_interface_srrp_statistics_advertisement_interval_discards{source=~\".*bngt-bng2\", srrp_srrp_id=\"1\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Syslog Event Count",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (application, level, source) (count_over_time({job=\"syslog\"}[$__auto]))",
     "legendFormat": "{{application}} {{level}} {{source}}"
    }
   ]
  },
  {
   "title": "Master / NoN Master Transitions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "state_service_vprn_subscriber_interface_group_interface_srrp_statistics_become_master{source=~\".*bngt-bng1\", srrp_srrp_id=\"1\"}",
     "legendFormat": "Become Master {{source}}"
    },
    {
     "expr": "state_service_vprn_subscriber_interface_group_interface_srrp_statistics_become_master{source=~\".*bngt-bng2\", srrp_srrp_id=\"1\"}",
     "legendFormat": "Become Master {{source}}"
    },
    {
     "expr": "state_service_vprn_subscriber_interface_group_interface_srrp_statistics_become_non_master{source=~\".*bngt-bng1\", srrp_srrp_id=\"1\"}",
     "legendFormat": "Become NoN Master {{source}}"
    },
    {
     "expr": "state_service_vprn_subscriber_interface_group_interface_srrp_statistics_become_non_master{source=~\".*bngt-bng2\", srrp_srrp_id=\"1\"}",
     "legendFormat": "Become NoN Master {{source}}"
    }
   ]
  },
  {
   "title": "Syslog",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"syslog\"}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "BNG CPU Usage, %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "state_system_cpu_summary_usage_cpu_usage{cpu_sample_period=\"60\", source=~\".*bng[1,2]\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Memory Used, %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 35 },
   "targets": [
    {
     "expr": "sum by(source) (state_system_memory_pools_summary_total_in_use)/ on(source)(sum by(source) (state_system_memory_pools_summary_total_in_use) + sum by(source) (state_system_memory_pools_summary_available_memory)) * 100",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Peak IPv4 / IPv6 hosts",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_subscriber_mgmt_statistics_total_hosts_peak_value{total_hosts_counter=\"ipv4\"}",
     "legendFormat": "{{source}} {{total_hosts_counter}}"
    },
    {
     "expr": "state_subscriber_mgmt_statistics_total_hosts_peak_value{total_hosts_counter=\"ipv6\"}",
     "legendFormat": "{{source}} {{total_hosts_counter}}"
    }
   ]
  },
  {
   "title": "Number of current IPv4 / IPv6 hosts",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_subscriber_mgmt_statistics_total_hosts_current_value{total_hosts_counter=\"ipv4\"}",
     "legendFormat": "{{source}} {{total_hosts_counter}}"
    },
    {
     "expr": "state_subscriber_mgmt_statistics_total_hosts_current_value{total_hosts_counter=\"ipv6\"}",
     "legendFormat": "{{source}} {{total_hosts_counter}}"
    }
   ]
  },
  {
   "title": "SAP instances allocated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "state_card_mda_resource_usage_sap_instances_allocated{mda_mda_slot=\"1\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Igress / Egress Policers allocated, %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "( state_card_fp_resource_usage_egress_policers_allocated / on (source) state_card_fp_resource_usage_egress_policers_total) * 100",
     "legendFormat": "{{source}} ingress"
    },
    {
     "expr": "( state_card_fp_resource_usage_ingress_policers_allocated / on (source) state_card_fp_resource_usage_ingress_policers_total) * 100",
     "legendFormat": "{{source}} egress"
    }
   ]
  },
  {
   "title": "Total PPP session established",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "state_subscriber_mgmt_statistics_sessions_current_value{sessions_counter=\"ppp-sessions-total-established\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Igress / Egress Queues allocated, %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "( state_card_fp_resource_usage_egress_queues_allocated/ on (source) state_card_fp_resource_usage_egress_queues_total) * 100",
     "legendFormat": "{{source}} ingress"
    },
    {
     "expr": "(state_card_fp_resource_usage_ingress_queues_allocated / on (source) state_card_fp_resource_usage_egress_queues_total) * 100",
     "legendFormat": "{{source}} egress"
    }
   ]
  },
  {
   "title": "Next hop resource entries consumed, %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "( state_system_resource_usage_subscriber_next_hop_entries_allocated{subscription_name=~\".*sros-system-resources\"} / on (source) state_system_resource_usage_subscriber_next_hop_entries_total{subscription_name=~\".*sros-system-resources\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Ingress Port Rates on BNG",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "rate(state_port_ethernet_statistics_in_octets{subscription_name=~\".*sros-router-interfaces\", source=~\".*bng[1,2]\", port_port_id=~\"1/1/.*/1\"}[60s]) * 8 / 60000",
     "legendFormat": "in {{port_port_id}} {{source}}"
    }
   ]
  },
  {
   "title": "Ingress Port Errors on BNG",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "rate(state_port_ethernet_statistics_in_errors{subscription_name=~\".*sros-router-interfaces\", source=~\".*bng[1,2]\", port_port_id=~\"1/1/.*/1\"}[60s]) * 8 / 60000",
     "legendFormat": "in {{port_port_id}} {{source}}"
    }
   ]
  },
  {
   "title": "Egress Port Rates on BNG",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "rate(state_port_ethernet_statistics_out_octets{subscription_name=~\".*sros-router-interfaces\", source=~\".*bng[1,2]\", port_port_id=~\"1/1/.*/1\"}[60s]) * 8 / 60000",
     "legendFormat": "in {{port_port_id}} {{source}}"
    }
   ]
  },
  {
   "title": "Egress Port Errors on BNG",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "rate(state_port_ethernet_statistics_out_errors{subscription_name=~\".*sros-router-interfaces\", source=~\".*bng[1,2]\", port_port_id=~\"1/1/.*/1\"}[60s]) * 8 / 60000",
     "legendFormat": "in {{port_port_id}} {{source}}"
    }
   ]
  }
 ]
}