{
 "title": "SDCIO Config Management",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total Targets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sdcio_target_config_ready) OR vector(0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "UnSync Targets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sdcio_target_config_ready == 0) OR vector(0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sync Targets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sdcio_target_config_ready == 1) or vector(0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Top 10 Target Deviations (Brown Field)",
   "type": "bargauge",
   "description": "Configuration imported to the cluster for prevalidation.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,sort_desc(sdcio_deviation_count{type=\"target\"}))",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Total Configs Intents",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sdcio_config_ready) OR vector(0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "UnSync Config Intents",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sdcio_config_ready == 0) OR vector(0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sync Config Intents",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sdcio_config_ready == 1) or vector(0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Top 10 Config Deviations",
   "type": "bargauge",
   "description": "Configuration imported to the cluster for prevalidation.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,sort_desc(sdcio_deviation_count{type=\"config\"}))",
     "legendFormat": "{{resource_name}}"
    }
   ]
  }
 ]
}